# Generated by Django 2.2.19 on 2022-01-24 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('posts', '0001_initial'), ('posts', '0002_auto_20220122_1226'), ('posts', '0003_auto_20220122_1651'), ('posts', '0004_auto_20220122_1703'), ('posts', '0005_auto_20220122_1708'), ('posts', '0006_auto_20220124_1226')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимальная длина названия 200 символов.', max_length=200, verbose_name='Название группы')),
                ('slug', models.SlugField(help_text='Уникальный адрес группы, часть URL (например, для группы любителей котиков slug будет равен cats: group/cats).', unique=True, verbose_name='Адрес группы')),
                ('description', models.TextField(help_text='Текст, описывающий сообщество. Этот текст будет отображаться на странице сообщества.', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа для записей',
                'verbose_name_plural': 'Группы для записей',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст записи')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('group', models.ForeignKey(blank=True, help_text='Привязка к конкретной группе записей', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_posts', to='posts.Group', verbose_name='Группа записей')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-pub_date'],
            },
        ),
    ]
