# Generated by Django 2.2.19 on 2022-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220122_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Уникальный адрес группы, часть URL (например, для группы любителей котиков slug будет равен cats: group/cats).', unique=True, verbose_name='Адрес группы'),
        ),
    ]
